import { NextPage } from "next";
import { useEffect } from "react";
import { useTranslation } from "react-i18next";
import Head from "next/head";
import Header from "@/layouts/Header";
import { Box, Grid } from "@mui/material";
import { PropertyCard } from "@/modules/Property/Components";
import BestWidth from "@/components/BestWidth";

const Test: NextPage = () => {
  const { t } = useTranslation();

  useEffect(() => {
    window.close();
  }, []);

  return (
    <>
      <Head>
        <title>{t("pageIndex")}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Box sx={{ display: "flex", justifyContent: "center" }}>
        <BestWidth>
          <Grid container spacing={3} sx={{ px: 1, py: 3 }}>
            {Array(10).map((i) => (
              <Grid key={i} item md={3}>
                <PropertyCard />
              </Grid>
            ))}
            <Grid item md={3}>
              <PropertyCard />
            </Grid>
            <Grid item md={3}>
              <PropertyCard />
            </Grid>
            <Grid item md={3}>
              <PropertyCard />
            </Grid>
            <Grid item md={3}>
              <PropertyCard />
            </Grid>
            <Grid item md={3}>
              <PropertyCard />
            </Grid>
            <Grid item md={3}>
              <PropertyCard />
            </Grid>
            <Grid item md={3}>
              <PropertyCard />
            </Grid>
            <Grid item md={3}>
              <PropertyCard />
            </Grid>
            <Grid item md={3}>
              <PropertyCard />
            </Grid>
            <Grid item md={3}>
              <PropertyCard />
            </Grid>
            <Grid item md={3}>
              <PropertyCard />
            </Grid>
            <Grid item md={3}>
              <PropertyCard />
            </Grid>
            <Grid item md={3}>
              <PropertyCard />
            </Grid>
            <Grid item md={3}>
              <PropertyCard />
            </Grid>
            <Grid item md={3}>
              <PropertyCard />
            </Grid>
            <Grid item md={3}>
              <PropertyCard />
            </Grid>
            <Grid item md={3}>
              <PropertyCard />
            </Grid>
          </Grid>
        </BestWidth>
      </Box>
    </>
  );
};

export default Test;
